name: visual-excuses
base: core20
version: '0.4'
summary: Visual Graph Representation of Ubuntu Archive Proposed Migration Status
description: Create dynamic relation graph representing proposed migration
grade: stable
confinement: strict

parts:
  visual-excuses:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    stage-packages:
      - python3-wheel
    python-packages:
      - pyyaml
      - requests
      - pyvis
    source: .

apps:
  visual-excuses:
    command: bin/visual-excuses
    plugs:
      - network
      - home
      - desktop
    environment:
      LANG: C.UTF-8

